manifest:
  remotes:
    - name: dcpedit
      url-base: https://github.com/dcpedit
  projects:
    - name: zmk
      remote: dcpedit
      revision: pillzmod
      import: app/west.yml
  self:
    path: config